# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Inner Machinations
description: >- # this means to ignore newlines until "baseurl:"
  This is a plase for me to talk more about things that interest me, ranging
  from computer science to music to philosophy to sports.
#baseurl: "/blog" # the subpath of your site, e.g. /blog
url: "nate-browne.github.io" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
markdown: kramdown
theme: jekyll-theme-console
plugins:
  - jekyll-relative-links
  - jekyll-feed
  - jekyll-seo-tag

relative_links:
  enabled: true
  collections: true

header_pages:


footer: 'Copyright &copy; 2019 Nate Browne <a href="https://nate-browne.github.io">Main site</a>'

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
